#COMMON APPLICATION CONFIGURATIONS

#Server Configuration
server:
 port: 9092
 
#Logging Configuration
logging:
  level:
    org:
      springframework: info
    com:
      bugtracking: debug
  file:
    name: bugtrackingapi.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    
#URL Configutation of another microservice
application:
 url: http://localhost:8090/api/v1/applications
